<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="IN00302" name="testcases.Transactions_Module" tests="1" failures="0" timestamp="08 Feb 2019 11:57:25 GMT" time="53.138" errors="1">
  <testcase name="Transactions_Module_010" time="53.138" classname="testcases.Transactions_Module">
    <error type="exceptions.SeleniumExceptions" message="Database column &#039;CommNotes&#039; with value &#039;SUT_RE&#039; does not matches with portal value &#039;&#039;">
      <![CDATA[exceptions.SeleniumExceptions: Database column 'CommNotes' with value 'SUT_RE' does not matches with portal value ''
at helper.CommonKeywords.compareWithDB(CommonKeywords.java:975)
at helper.CommonKeywords.getWebelementAction(CommonKeywords.java:235)
at readexcel.ReadProjectReusables.performAction(ReadProjectReusables.java:223)
at readexcel.ReadProjectReusables.getActionSteps1(ReadProjectReusables.java:190)
at readexcel.TestcaseFlow.runSingleTest(TestcaseFlow.java:43)
at testcases.Transactions_Module.Transactions_Module_010(Transactions_Module.java:9)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Transactions_Module_010 -->
</testsuite> <!-- testcases.Transactions_Module -->
